Задания:
1. Импорт библиотеки NumPy с общепринятым сокращением.
2. Примеры создания массивов:
   - из обычных списков;
   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.
3. Демонстрация атрибутов:
   - вывод формы (shape) и типа данных (dtype) для одного из массивов.
4. Примеры индексирования и срезов:
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.
5. Примеры векторных операций и базовых статистик:
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.

1) Импорт библиотеки NumPy

In [5]:
import numpy as np 

2) Создание массивов

In [6]:
a = np.array([11,22,33,44,55]) #одномерный массив
a

array([11, 22, 33, 44, 55])

In [7]:
b = np.array([[1, 5, 6], [4, 5, 10]]) #двумерный массив-матрица
b

array([[ 1,  5,  6],
       [ 4,  5, 10]])

In [8]:
z = np.zeros((4,10)) #двумерный массив из нулей, размером 4 на 10
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
o = np.ones((2,2,3)) #трехмерный массив из единиц размером 2 на 2 на 3
o

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [10]:
e = np.eye(6) #единичную матрицу
e

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [11]:
c = np.arange(100,1000,10) #последовательность чисел от 100 до 1000 с шагом 10, 1000-не входит
c

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220,
       230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350,
       360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480,
       490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 600, 610,
       620, 630, 640, 650, 660, 670, 680, 690, 700, 710, 720, 730, 740,
       750, 760, 770, 780, 790, 800, 810, 820, 830, 840, 850, 860, 870,
       880, 890, 900, 910, 920, 930, 940, 950, 960, 970, 980, 990])

In [12]:
r = np.arange(4, 2, -0.1)
r

array([4. , 3.9, 3.8, 3.7, 3.6, 3.5, 3.4, 3.3, 3.2, 3.1, 3. , 2.9, 2.8,
       2.7, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1])

In [13]:
f = np.full((2, 3), 7) #массив, заполненный заданным числом
f

array([[7, 7, 7],
       [7, 7, 7]])

3) Демонстрация атрибутов

In [14]:
print("Форма массива:", f.shape) #число строк и столбцов
print("Тип данных:", f.dtype) #тип элементов массива

Форма массива: (2, 3)
Тип данных: int64


4) Примеры индексирования и срезов

In [15]:
s = np.random.random(5)
s

array([0.67143658, 0.90667369, 0.94467587, 0.35715732, 0.62017944])

In [16]:
e1 = s[4] #4 индекс элемента
e1

np.float64(0.620179437754772)

In [17]:
e2 = s[1:] #с индекса 1 до конца
e2

array([0.90667369, 0.94467587, 0.35715732, 0.62017944])

In [18]:
e3 = s[::-1] #обратный порядок
e3

array([0.62017944, 0.35715732, 0.94467587, 0.90667369, 0.67143658])

In [19]:
s2 = np.random.random((5,5))
s2

array([[0.79956632, 0.23641279, 0.30819671, 0.29406154, 0.75647931],
       [0.41832091, 0.21244605, 0.49263282, 0.63262516, 0.51801684],
       [0.98753644, 0.49420398, 0.8113911 , 0.33673167, 0.9286839 ],
       [0.6515756 , 0.89028261, 0.45044445, 0.84128712, 0.48863977],
       [0.51814291, 0.59175738, 0.82443937, 0.21705272, 0.73978633]])

In [20]:
e4 = s2[2,3] #элемент в 3 строке и 4 столбце
e5 = s2[3,4] #элемент в 4 строке и 5 столбце
print(e4, e5)

0.3367316723285456 0.48863977121728686


5) Примеры векторных операций и базовых статистик

In [21]:
y = np.array([1, 2, 3, 4])
u = np.array([10, 20, 30, 40])
c_mul = u * y      #Поэлементное сложение
c_sum = u+y        #Поэлементное сложение
print("Сумма:", c_sum)
print("Произведение:", c_mul)

Сумма: [11 22 33 44]
Произведение: [ 10  40  90 160]


In [22]:
m1 = np.array([[1, 2],
               [3, 4]])

m2 = np.array([[10, 20],
               [30, 40]])
print(m1 + m2)
print(m1 * m2)

[[11 22]
 [33 44]]
[[ 10  40]
 [ 90 160]]


In [23]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Среднее по всем элементам:", m.mean()) # Среднее по всей матрице
print("Среднее по строкам:", m.mean(axis=1))  # Среднее по строкам (axis=1)
print("Среднее по столбцам:", m.mean(axis=0)) # Среднее по столбцам (axis=0)

Среднее по всем элементам: 3.5
Среднее по строкам: [2. 5.]
Среднее по столбцам: [2.5 3.5 4.5]


In [24]:
t = np.random.sample(5)
print("Матрица:", t)
print("Среднее:", t.mean())                 # Среднее значение
print("Сумма:", t.sum())                    # Сумма
print("Минимум:", t.min())                  # Минимум
print("Максимум:", t.max())                 # Максимум

Матрица: [0.73437289 0.86743217 0.13000139 0.07041895 0.85120214]
Среднее: 0.5306855059608384
Сумма: 2.6534275298041923
Минимум: 0.07041894927970549
Максимум: 0.8674321660515877
